### ISSUE TITLE
Add DB inside pods

### ISSUE THREAD

**Issue by NazarYavornytskyy** [GluuFederation/ox-push2-ios-pod#1]
So, current DB won't work with ox-push2 cocoa pod, we should change it to using NSUserDefaults instead

**Comment by nynymike** [comment]
ok, please proceed.

**Comment by NazarYavornytskyy** [comment]
Done, now our cocoa pod ox-push2 is using NSUserDefaults storage instead of CoreData which isn't supporting inside cocoa pod project. Next we should update changes in Cocoa Pods Main Storage and update version

**Comment by NazarYavornytskyy** [comment]
Done!
